# Synthesizable SoC RTL. setup_env.sh defines RTL_DIR before verilog_sub reads it.
$RTL_DIR/soc/rv_soc_pkg.sv
$RTL_DIR/rv_ooo_pkg.sv
$RTL_DIR/soc/rv_axi4_if.sv
$RTL_DIR/soc/rv_local_mem_if.sv
$RTL_DIR/frontend/rv_c_expander.sv
$RTL_DIR/frontend/rv_fetch_queue.sv
$RTL_DIR/frontend/rv_fetch_target_buffer.sv
$RTL_DIR/frontend/rv_branch_predictor.sv
$RTL_DIR/backend/rv_decode2.sv
$RTL_DIR/backend/rv_lsq_order_check.sv
$RTL_DIR/backend/rv_lsu_pipe.sv
$RTL_DIR/backend/rv_lsq.sv
$RTL_DIR/backend/rv_store_buffer.sv
$RTL_DIR/backend/rv_lsu_cluster.sv
$RTL_DIR/backend/rv_rename2.sv
$RTL_DIR/backend/rv_phys_regfile.sv
$RTL_DIR/backend/rv_issue_queue.sv
$RTL_DIR/backend/rv_issue_arbiter.sv
$RTL_DIR/backend/rv_int_alu.sv
$RTL_DIR/backend/rv_branch_unit.sv
$RTL_DIR/backend/rv_multiplier.sv
$RTL_DIR/backend/rv_divider.sv
$RTL_DIR/backend/rv_fpu.sv
$RTL_DIR/backend/rv_writeback_arbiter.sv
$RTL_DIR/backend/rv_branch_recovery.sv
$RTL_DIR/backend/rv_exec_result_buffer.sv
$RTL_DIR/backend/rv_csr_file.sv
$RTL_DIR/backend/rv_pmp.sv
$RTL_DIR/backend/rv_trap_controller.sv
$RTL_DIR/backend/rv_fence_controller.sv
$RTL_DIR/backend/rv_rob.sv
$RTL_DIR/frontend/rv_frontend.sv
$RTL_DIR/backend/rv_backend.sv
$RTL_DIR/rv_ooo_core.sv
$RTL_DIR/soc/rv_local_to_axi_bridge.sv
$RTL_DIR/soc/rv_axi_to_local_bridge.sv
$RTL_DIR/soc/rv_axi_error_slave.sv
$RTL_DIR/soc/rv_axi_xbar.sv
$RTL_DIR/soc/rv_soc_map_check.sv
$RTL_DIR/soc/rv_soc_addr_decode.sv
$RTL_DIR/soc/rv_sram_1r1w.sv
$RTL_DIR/soc/rv_tim_2bank.sv
$RTL_DIR/soc/rv_clint.sv
$RTL_DIR/soc/rv_bootrom.sv
$RTL_DIR/soc/rv_hostif.sv
$RTL_DIR/soc/rv_plic.sv
$RTL_DIR/soc/rv_d_fabric.sv
$RTL_DIR/soc/rv_i_fabric.sv
$RTL_DIR/soc/rv_soc_top.sv
